### ISSUE TITLE
Kledo API in Python

### ISSUE THREAD

**Issue by cloned-doy** [Kledo-ID/php-oauth2-demo#2]
hi permisi, I love Kledo and I'm going to use Kledo as my main platform to help me maintain my small business. I m going to sync my customer contacts and products in to Kledo thru the Kledo API (https://api.kledo.com/documentation). 

Initially, I have 200+ customer contacts and 1000+ sales history, Im planning to sync my data to Kledo by using some simple Requests python script.

Im trying to interact with Kledo API using simple python Requests, but since Im a python beginner, the API just throwing me 401 Unauthorized/Unauthenticated error messages. 

Is there some Python based examples (some random repository is perfectly ok) that can help me interact with the Kledo API? Terima kasih.

**Comment by PanjiNamjaElf** [comment]
There is no example oauth2 using Python on Kledo
Maybe you can read this php source how to integrate using Kledo API and you can convert it to your Python script maybe using some framework like Django
=> https://docs.djangoproject.com/en/4.1/ref/request-response/

Since u not put access token on Authorization header u will get response 401 Unauthorized/Unauthenticated.
You must request the access token first using Kledo OAuth App and put it on Authorization header when u want to make API Request...
Or maybe you can get the access token on the Kledo API Docs on `authentication/singleLogin` and u will get the access token on there...

Here some example php source to get access token:

Redirecting For Authorization => https://github.com/Kledo-ID/php-oauth2-demo/blob/master/authorization.php
Converting Authorization Codes To Access Tokens =>https://github.com/Kledo-ID/php-oauth2-demo/blob/master/callback.php

Example Request for Finance Account Resource => https://github.com/Kledo-ID/php-oauth2-demo/tree/master/demo/accounts
